### ISSUE TITLE
Please update for iOS 8 and Admob 7.0 SDK

### ISSUE THREAD

**Issue by phix23** [muccy/MUKAdMobViewController#1]
This  Cocoa Pod currently depends on Google-Mobile-Ads-SDK v6.6 which does not officially support iOS 8. The dependency should be updated to use the newest SDK.

When running on iOS 8 the following message is printed in the console:

> You are currently using version 6.12.2 of the SDK, which doesn't officially support iOS 8. Please consider updating your SDK to the most recent sdk version, 7.0.0, to get iOS 8 support, including a fix for smart banner rendering in landscape mode. The latest SDK can be downloaded from http://goo.gl/iGzfsP. A full list of release notes is available at https://developers.google.com/mobile-ads-sdk/docs/admob/ios/rel-notes.

**Comment by muccy** [comment]
I know. I have an issue with CocoaPods: https://github.com/CocoaPods/CocoaPods/issues/3161

**Comment by phix23** [comment]
The CocoaPods issue has been closed. Any chance of getting this fixed and upgrade to the latest SDK?

**Comment by muccy** [comment]
I'm dealing with an error I reported to [Google SDK groups](https://groups.google.com/d/topic/google-admob-ads-sdk/gN5T9y6IHjM/discussion]).

**Comment by phix23** [comment]
This should be easy to fix:
- Use framework imports in MUKAdMobViewController.h and *.m like this:

```
#import <GoogleMobileAds/GADBannerView.h>
#import <GoogleMobileAds/GADInterstitial.h>
```
- Set the deployment target of the example target to iOS 6.1 (compile with iOS 6.0 fails)
- don't use the precompiled header to import AdViewController.h, this also causes problems
- make some adjustments to fix the remaining errors and warnings related to Google Ads SDK 7.4

**Comment by muccy** [comment]
Version 1.2.6 is up. Thank you :)
